### ISSUE TITLE
Compiled layout.css.scss is missing assets prefix

### ISSUE THREAD

**Issue by hopewise** [refinery/refinerycms#2180]
I am sorry to post this issue, as I tried post it at google group, I couldn't wait as its very important ..

Though, I am writing more details here

In the `layout.css.scss`, an image for background is targeted like this:

``` scss
body {
  min-height: 100%;
  margin: 0;
  padding: 0;
  font-size: 10px;
  font-family: Verdana;
  line-height: 1.5em;
  background: #303030 image_url('refinery/page_bg.png') repeat;
}
```

And when is compiled, it will be like this:

``` scss
background: #303030 image_url('refinery/page_bg.png') repeat;
```

But, page_bg.png is in the assets folder: `assets/refinery/page_bg.png`

If I try www.mydomain.com/assets/refinery/page_bg.png I can see the image, `image_url('refinery/page_bg.png')` in the compiled scss is missing the prefix assets/
www.mydomain.com/refinery/page_bg.png won't show the image

How can I fix this?

I tried to create a folder in public folder named refinery and put page_bg.png inside it, but, I didn't work, and www.mydomain.com/refinery/page_bg.png won't show the image .

Is there a solution for this? any one can help? fixing the assets prefix is of course better, but, I don't mind using the public folder directly ..

Thanks very much
